
package com.DistributedSystems.asg3.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RoomRecordsService", targetNamespace = "http://remote.asg3.DistributedSystems.com/", wsdlLocation = "file:/X:/Code/DistributedSystems/src/com/DistributedSystems/RoomRecords.wsdl")
public class RoomRecordsService
    extends Service
{

    private final static URL ROOMRECORDSSERVICE_WSDL_LOCATION;
    private final static WebServiceException ROOMRECORDSSERVICE_EXCEPTION;
    private final static QName ROOMRECORDSSERVICE_QNAME = new QName("http://remote.asg3.DistributedSystems.com/", "RoomRecordsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/X:/Code/DistributedSystems/src/com/DistributedSystems/RoomRecords.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROOMRECORDSSERVICE_WSDL_LOCATION = url;
        ROOMRECORDSSERVICE_EXCEPTION = e;
    }

    public RoomRecordsService() {
        super(__getWsdlLocation(), ROOMRECORDSSERVICE_QNAME);
    }

    public RoomRecordsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROOMRECORDSSERVICE_QNAME, features);
    }

    public RoomRecordsService(URL wsdlLocation) {
        super(wsdlLocation, ROOMRECORDSSERVICE_QNAME);
    }

    public RoomRecordsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROOMRECORDSSERVICE_QNAME, features);
    }

    public RoomRecordsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RoomRecordsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IRoomRecords
     */
    @WebEndpoint(name = "RoomRecordsPort")
    public IRoomRecords getRoomRecordsPort() {
        return super.getPort(new QName("http://remote.asg3.DistributedSystems.com/", "RoomRecordsPort"), IRoomRecords.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IRoomRecords
     */
    @WebEndpoint(name = "RoomRecordsPort")
    public IRoomRecords getRoomRecordsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://remote.asg3.DistributedSystems.com/", "RoomRecordsPort"), IRoomRecords.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ROOMRECORDSSERVICE_EXCEPTION!= null) {
            throw ROOMRECORDSSERVICE_EXCEPTION;
        }
        return ROOMRECORDSSERVICE_WSDL_LOCATION;
    }

}
