package com.DistributedSystems.asg2.RoomRecordsObj;


/**
* RoomRecordsObj/RoomRecordsCorba.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./RoomRecords.idl
* Saturday, October 16, 2021 2:48:33 o'clock PM EDT
*/

public interface RoomRecordsCorba extends RoomRecordsCorbaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
}
