package com.DistributedSystems.asg2.RoomRecordsObj;


/**
* RoomRecordsObj/RoomRecordsCorbaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./RoomRecords.idl
* Saturday, October 16, 2021 2:48:33 o'clock PM EDT
*/

abstract public class RoomRecordsCorbaHelper
{
  private static String  _id = "IDL:RoomRecordsObj/RoomRecordsCorba:1.0";

  public static void insert (org.omg.CORBA.Any a, RoomRecordsCorba that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RoomRecordsCorba extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (RoomRecordsCorbaHelper.id (), "RoomRecordsCorba");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RoomRecordsCorba read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RoomRecordsCorbaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RoomRecordsCorba value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static RoomRecordsCorba narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RoomRecordsCorba)
      return (RoomRecordsCorba)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _RoomRecordsCorbaStub stub = new _RoomRecordsCorbaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static RoomRecordsCorba unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RoomRecordsCorba)
      return (RoomRecordsCorba)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _RoomRecordsCorbaStub stub = new _RoomRecordsCorbaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
