package com.DistributedSystems.asg2.RoomRecordsObj;


/**
* RoomRecordsObj/RoomRecordsCorba.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RoomRecords.idl
* Friday, October 15, 2021 9:26:23 o'clock PM EDT
*/

public interface RoomRecordsCorba extends RoomRecordsCorbaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface RoomRecordsCorba
